version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  frontend:
    docker:
      - image: cimg/node:15.0-browsers
    working_directory: ~/src/frontend
    steps:
      - checkout
      
      - run: pwd
      - run: ls -la

      
      - run: yarn install
   

workflows:
  deploy:
    jobs:
      - frontend
  app-tests:
    jobs:
      - node/test