version: 2.1
orbs:
  node: circleci/node@4.0.0
  aws-s3: circleci/aws-s3@1.0.11
  aws-cli: circleci/aws-cli@1.3.0


jobs:
  frontend:
    docker:
      - image: cimg/node:15.0-browsers
    working_directory: ~/src/frontend
    steps:
      - checkout
      - run: pwd
      - run: ls -la
      - run: yarn install
      - run: sudo apt-get install python3-venv
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - aws-s3/sync:
          from: bucket
          to: 's3://pythonlearningatmac/'
workflows:
  deploy:
    jobs:
      - frontend
  app-tests:
    jobs:
      - node/test