version: 2.1
jobs:
  frontend:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/src/frontend
    steps:
      - checkout

workflows:
  node-tests:
    jobs:
      - node/test

  workflow name:
    jobs:
      - frontend
