version: 2.1
orbs:
  aws-s3:circleci/aws-s3@1.0.11
jobs:
  frontend:
    docker:
      - image: cimg/node:15.0-browsers
    working_directory: ~/src/frontend
    steps:
      - checkout
      - setup_remote_docker
      
      - run: yarn install

      - aws-s3/sync:
        from: build
        to: 's3://cra-ci-demo/'
        arguments: |
          --acl public-read \
          --cache-control "max-age=86400"
        overwrite: true

workflows:
  deploy:
    jobs:
      - frontend