version: 2.1
jobs:
  frontend:
    docker:
      - image: circleci/node:12.9.1-browser
    working_directory: ~/src/frontend
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
          - node_modules
          - ~/.npm
          - ~/.cache

          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn-test
      - run: npm install
      - run: npm start

workflows:
  deploy:
    jobs:
      - frontend