version: 2.1
orbs:
  node: circleci/node@4.0.0
  aws-s3: circleci/aws-s3@1.0.11
  aws-cli: circleci/aws-cli@1.3.0
  python: circleci/python@1.2.1


jobs:
  frontend:
    docker:
      - image: cimg/node:15.0-browsers
    working_directory: ~/src/front-end
    steps:
      - checkout
      - run: pwd
      - run: ls -la
      - run: yarn install
      - run: cd front-end/ && npm run build
      
  aws:
    docker:
      - image: cimg/python:3.9.0
    working_directory: ~/src
    steps:
      - run: pwd
      - run: ls
      - aws-cli/install
      - aws-cli/setup
      - aws-s3/sync:
          from: "front-end/build"
          to: "s3://pythonlearningatmac"
workflows:
  deploy:
    jobs:
      - frontend
      - aws
  app-tests:
    jobs:
      - node/test