version: 2.1
jobs:
  frontend:
    docker:
      - image: circleci/node:12.9.1-browser
    working_directory: ~/src/frontend
    steps:
      - checkout

workflows:
  deploy:
    jobs:
      - frontend