version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  frontend:
    docker:
      - image: circleci/node@3.0.0
    working_directory: ~/src/frontend
    steps:
      checkout ~/src





workflows:
  node-tests:
    jobs:
      - node/test

  workflow name:
    jobs:
      - frontend
