version: 2.1
orbs:
  node: circleci/node@4.0.0
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  frontend:
    docker:
      - image: cimg/node:15.0-browsers
    working_directory: ~/src/frontend
    steps:
      - checkout
      - run: pwd
      - run: ls -la
      - run: yarn install
      - aws-s3/sync:
        arguments: |
          --acl public-read \
          --cache-control "max-age=86400"
        aws-access-key-id: AWS_ACCESS_KEY_ID
        aws-region: AWS_REGION
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY
        from: bucket
        to: 's3://pythonlearningatmac'

workflows:
  deploy:
    jobs:
      - frontend
  app-tests:
    jobs:
      - node/test