use pythonlearning;
 
 #Q1
INSERT INTO Questions (name, description, tags, difficulty) values ( 'Hello to the world of coding!', 'Write could which will print the following statement: “Hello world, here I am!”. ', 'PrintStatement', 'easy');
INSERT INTO Tutorials (description, code) values ('Print Statements', 'This question is asking you to use Python’s built-in function print(). Functions are a topic that will be covered later on, but for now all you need to know is that Python has some built-in functions which take some input between the brackets and can perform some operations. print() is one of those built-in functions. Whatever you put in between the brackets of a print statement will be displayed on the screen. For example, if you write print(2) you should see a 2 appear on the screen. An important note is that any letters or words need to be surrounded by quotes. We will dive into the reason for quotes around words later on, but for now always wrap words and letters with quotes. For example, print(“Sally”) the word Sally will be displayed. The built-in print function is often used by beginners and experts alike to debug code and is an important tool in your toolkit.');
INSERT INTO Testcases (name, description, code) values ('Print Statements', '');

 #Q2
INSERT INTO Questions (name, description, tags, difficulty) values ( 'Hello to the world of coding!', 'Write could which will print the following statement: “Hello world, here I am!”. ', 'PrintStatement', 'easy');
INSERT INTO Tutorials (description, code) values ('Print Statements', 'This question is asking you to use Python’s built-in function print(). Functions are a topic that will be covered later on, but for now all you need to know is that Python has some built-in functions which take some input between the brackets and can perform some operations. print() is one of those built-in functions. Whatever you put in between the brackets of a print statement will be displayed on the screen. For example, if you write print(2) you should see a 2 appear on the screen. An important note is that any letters or words need to be surrounded by quotes. We will dive into the reason for quotes around words later on, but for now always wrap words and letters with quotes. For example, print(“Sally”) the word Sally will be displayed. The built-in print function is often used by beginners and experts alike to debug code and is an important tool in your toolkit.');
INSERT INTO Testcases (name, description, code) values ('Print Statements', '');

 #Q3
INSERT INTO Questions (name, description, tags, difficulty) values ( 'Hello to the world of coding!', 'Write could which will print the following statement: “Hello world, here I am!”. ', 'PrintStatement', 'easy');
INSERT INTO Tutorials (description, code) values ('Print Statements', 'This question is asking you to use Python’s built-in function print(). Functions are a topic that will be covered later on, but for now all you need to know is that Python has some built-in functions which take some input between the brackets and can perform some operations. print() is one of those built-in functions. Whatever you put in between the brackets of a print statement will be displayed on the screen. For example, if you write print(2) you should see a 2 appear on the screen. An important note is that any letters or words need to be surrounded by quotes. We will dive into the reason for quotes around words later on, but for now always wrap words and letters with quotes. For example, print(“Sally”) the word Sally will be displayed. The built-in print function is often used by beginners and experts alike to debug code and is an important tool in your toolkit.');
INSERT INTO Testcases (name, description, code) values ('Print Statements', '');
